### ISSUE TITLE
npm run version broken

### ISSUE THREAD

**Issue by dotherightthing** [dotherightthing/wpdtrt-npm-scripts#10]
```
> npm run version --prefix $npm_package_config_wpdtrt_npm_scripts


> wpdtrt-npm-scripts@0.0.1 version /Users/dan/Websites/wpdtrt-dbth/node_modules/wpdtrt-npm-scripts
> node ./scripts/version/plugin-bump.js

(node:38485) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
/Users/dan/Websites/wpdtrt-dbth/node_modules/wpdtrt-npm-scripts/scripts/version/plugin-bump.js:1
import wpdtrtPluginBump from 'gulp-wpdtrt-plugin-bump';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)
    at Module._compile (internal/modules/cjs/loader.js:1111:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by dotherightthing** [comment]
Fixed gulp-wpdtrt-plugin-bump but CI build fails due to Travis issue - https://travis-ci.community/t/travis-ci-org-octokit-unauthorized-prevents-release-to-github/8113

**Comment by dotherightthing** [comment]
Could disable this task and manually version for release.
