### ISSUE TITLE
wordpress-plugin test runs in wrong directory

### ISSUE THREAD

**Issue by dotherightthing** [dotherightthing/wpdtrt-npm-scripts#22]
Mocha - `process.chdir` seems to be one level deeper each time?

```
1) scripts
       wordpress-plugin
         "before all" hook in "wordpress-plugin":
     Error: ENOENT: no such file or directory, chdir '/Users/dan/Websites/wpdtrt-npm-scripts/vendor/dotherightthing/wpdtrt-dbth/vendor/dotherightthing/wpdtrt' -> './vendor/dotherightthing/wpdtrt-gallery'
      at process.wrappedChdir [as chdir] (internal/bootstrap/switches/does_own_process_state.js:115:14)
      at Context.<anonymous> (/Users/dan/Websites/wpdtrt-npm-scripts/test/tasks/scripts.spec.js:191:25)
      at callFn (/Users/dan/Websites/wpdtrt-npm-scripts/node_modules/mocha/lib/runnable.js:387:21)
      at Hook.Runnable.run (/Users/dan/Websites/wpdtrt-npm-scripts/node_modules/mocha/lib/runnable.js:379:7)
      at next (/Users/dan/Websites/wpdtrt-npm-scripts/node_modules/mocha/lib/runner.js:384:10)
      at Immediate._onImmediate (/Users/dan/Websites/wpdtrt-npm-scripts/node_modules/mocha/lib/runner.js:425:5)
      at processImmediate (internal/timers.js:456:21)
```

**Comment by dotherightthing** [comment]
Fixed
