### ISSUE TITLE
npm run test fails

### ISSUE THREAD

**Issue by dotherightthing** [dotherightthing/wpdtrt-npm-scripts#51]
## The subversion command line tools are no longer provided by Xcode (macOS Catalina)

```node
dtrt:wpdtrt-table dan$ npm run test

> wpdtrt-table@0.1.0 test /Users/dan/Websites/wpdtrt-table
> npm run test --prefix $npm_package_config_wpdtrt_npm_scripts


> wpdtrt-npm-scripts@0.3.30 pretest /Users/dan/Websites/wpdtrt-table/node_modules/wpdtrt-npm-scripts
> node ./scripts/pretest/create-wp-test-environment.js

 
--------------------------------------------------------------------------------
05/08/2021, 00:53:07
wpdtrt-npm-scripts: test: create wp test environment (install wp test suite and
create database)
--------------------------------------------------------------------------------
 
error Error: Command failed with exit code 72: bash ./scripts/pretest/install-wp-tests.sh wpdtrt_npm_scripts_wpunit_1628081588008 latest
+ install_wp
+ '[' -d /var/folders/y4/x0wxcjc97qdg6wmwn8wvll7w0000gn/T/wordpress/ ']'
+ mkdir -p /var/folders/y4/x0wxcjc97qdg6wmwn8wvll7w0000gn/T/wordpress/
+ [[ latest == \n\i\g\h\t\l\y ]]
+ [[ latest == \t\r\u\n\k ]]
+ '[' latest == latest ']'
+ local ARCHIVE_NAME=latest
+ download https://wordpress.org/latest.tar.gz /var/folders/y4/x0wxcjc97qdg6wmwn8wvll7w0000gn/T/wordpress.tar.gz
++ which curl
+ '[' /Applications/MAMP/Library/bin/curl ']'
+ curl -s https://wordpress.org/latest.tar.gz
+ tar --strip-components=1 -zxmf /var/folders/y4/x0wxcjc97qdg6wmwn8wvll7w0000gn/T/wordpress.tar.gz -C /var/folders/y4/x0wxcjc97qdg6wmwn8wvll7w0000gn/T/wordpress/
+ download https://raw.github.com/markoheijnen/wp-mysqli/master/db.php /var/folders/y4/x0wxcjc97qdg6wmwn8wvll7w0000gn/T/wordpress//wp-content/db.php
++ which curl
+ '[' /Applications/MAMP/Library/bin/curl ']'
+ curl -s https://raw.github.com/markoheijnen/wp-mysqli/master/db.php
+ install_test_suite
++ uname -s
+ [[ Darwin == \D\a\r\w\i\n ]]
+ local 'ioption=-i .bak'
+ '[' '!' -d /var/folders/y4/x0wxcjc97qdg6wmwn8wvll7w0000gn/T/wordpress-tests-lib ']'
+ mkdir -p /var/folders/y4/x0wxcjc97qdg6wmwn8wvll7w0000gn/T/wordpress-tests-lib
+ svn co --quiet https://develop.svn.wordpress.org/tags/5.8/tests/phpunit/includes/ /var/folders/y4/x0wxcjc97qdg6wmwn8wvll7w0000gn/T/wordpress-tests-lib/includes
svn: error: The subversion command line tools are no longer provided by Xcode.
    at makeError (/Users/dan/Websites/wpdtrt-table/node_modules/execa/lib/error.js:59:11)
    at Function.module.exports.sync (/Users/dan/Websites/wpdtrt-table/node_modules/execa/index.js:188:17)
    at Function.module.exports.commandSync (/Users/dan/Websites/wpdtrt-table/node_modules/execa/index.js:227:15)
    at createWpTestEnvironment (/Users/dan/Websites/wpdtrt-table/node_modules/wpdtrt-npm-scripts/scripts/pretest/create-wp-test-environment.js:28:66)
    at Object.<anonymous> (/Users/dan/Websites/wpdtrt-table/node_modules/wpdtrt-npm-scripts/scripts/pretest/create-wp-test-environment.js:39:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  shortMessage: 'Command failed with exit code 72: bash ./scripts/pretest/install-wp-tests.sh wpdtrt_npm_scripts_wpunit_1628081588008 latest',
  command: 'bash ./scripts/pretest/install-wp-tests.sh wpdtrt_npm_scripts_wpunit_1628081588008 latest',
  exitCode: 72,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '+ install_wp\n' +
    "+ '[' -d /var/folders/y4/x0wxcjc97qdg6wmwn8wvll7w0000gn/T/wordpress/ ']'\n" +
    '+ mkdir -p /var/folders/y4/x0wxcjc97qdg6wmwn8wvll7w0000gn/T/wordpress/\n' +
    '+ [[ latest == \\n\\i\\g\\h\\t\\l\\y ]]\n' +
    '+ [[ latest == \\t\\r\\u\\n\\k ]]\n' +
    "+ '[' latest == latest ']'\n" +
    '+ local ARCHIVE_NAME=latest\n' +
    '+ download https://wordpress.org/latest.tar.gz /var/folders/y4/x0wxcjc97qdg6wmwn8wvll7w0000gn/T/wordpress.tar.gz\n' +
    '++ which curl\n' +
    "+ '[' /Applications/MAMP/Library/bin/curl ']'\n" +
    '+ curl -s https://wordpress.org/latest.tar.gz\n' +
    '+ tar --strip-components=1 -zxmf /var/folders/y4/x0wxcjc97qdg6wmwn8wvll7w0000gn/T/wordpress.tar.gz -C /var/folders/y4/x0wxcjc97qdg6wmwn8wvll7w0000gn/T/wordpress/\n' +
    '+ download https://raw.github.com/markoheijnen/wp-mysqli/master/db.php /var/folders/y4/x0wxcjc97qdg6wmwn8wvll7w0000gn/T/wordpress//wp-content/db.php\n' +
    '++ which curl\n' +
    "+ '[' /Applications/MAMP/Library/bin/curl ']'\n" +
    '+ curl -s https://raw.github.com/markoheijnen/wp-mysqli/master/db.php\n' +
    '+ install_test_suite\n' +
    '++ uname -s\n' +
    '+ [[ Darwin == \\D\\a\\r\\w\\i\\n ]]\n' +
    "+ local 'ioption=-i .bak'\n" +
    "+ '[' '!' -d /var/folders/y4/x0wxcjc97qdg6wmwn8wvll7w0000gn/T/wordpress-tests-lib ']'\n" +
    '+ mkdir -p /var/folders/y4/x0wxcjc97qdg6wmwn8wvll7w0000gn/T/wordpress-tests-lib\n' +
    '+ svn co --quiet https://develop.svn.wordpress.org/tags/5.8/tests/phpunit/includes/ /var/folders/y4/x0wxcjc97qdg6wmwn8wvll7w0000gn/T/wordpress-tests-lib/includes\n' +
    'svn: error: The subversion command line tools are no longer provided by Xcode.',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

> wpdtrt-npm-scripts@0.3.30 test /Users/dan/Websites/wpdtrt-table/node_modules/wpdtrt-npm-scripts
> ./scripts/test/phpunit.sh

 
--------------------------------------------------------------------------------
05/08/2021, 00:53:26
wpdtrt-npm-scripts: test: phpunit (run unit tests)
--------------------------------------------------------------------------------
 
phpunit not found, skipping
```

**Comment by dotherightthing** [comment]
https://stackoverflow.com/questions/63590208/package-phpunit-php-token-stream-is-abandoned-you-should-avoid-using-it-no-rep

**Comment by dotherightthing** [comment]
> The latest release of PHPUnit is 8.x, WordPress is currently only compatible with the 7.x release tree. Until [#46149](https://core.trac.wordpress.org/ticket/46149) is merged, the latest PHPUnit 7.x release should be used
>
> <https://make.wordpress.org/core/handbook/testing/automated-testing/phpunit/>

**Comment by dotherightthing** [comment]
Reverted version

```bash
 - Downgrading phpunit/phpunit (9.5.8 => 7.5.20): Loading from cache
```

**Comment by dotherightthing** [comment]
```bash
dtrt:wpdtrt-table dan$ npm run test

> wpdtrt-table@0.1.0 test /Users/dan/Websites/wpdtrt-table
> npm run test --prefix $npm_package_config_wpdtrt_npm_scripts


> wpdtrt-npm-scripts@0.3.30 pretest /Users/dan/Websites/wpdtrt-table/node_modules/wpdtrt-npm-scripts
> node ./scripts/pretest/create-wp-test-environment.js

 
--------------------------------------------------------------------------------
05/08/2021, 09:47:16
wpdtrt-npm-scripts: test: create wp test environment (install wp test suite and
create database)
--------------------------------------------------------------------------------
 

> wpdtrt-npm-scripts@0.3.30 test /Users/dan/Websites/wpdtrt-table/node_modules/wpdtrt-npm-scripts
> ./scripts/test/phpunit.sh

 
--------------------------------------------------------------------------------
05/08/2021, 09:47:18
wpdtrt-npm-scripts: test: phpunit (run unit tests)
--------------------------------------------------------------------------------
 
phpunit not found, skipping
dtrt:wpdtrt-table dan$ 
```

**Comment by dotherightthing** [comment]
```sh
cd /var/folders/y4/x0wxcjc97qdg6wmwn8wvll7w0000gn/T
open .
```

Deleted `wordpress` and `wordpress-tests-lib`.

```sh
npm run test
```

This worked.
