### ISSUE TITLE
Github action: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by dotherightthing** [dotherightthing/wpdtrt-npm-scripts#56]
```
TypeError: Cannot read properties of undefined (reading 'replace')
    at Suite.<anonymous> (/Users/dan/Websites/wpdtrt-npm-scripts/test/tasks/scripts.spec.js:128:53)
    at Object.create (/Users/dan/Websites/wpdtrt-npm-scripts/node_modules/mocha/lib/interfaces/common.js:140:19)
    at context.describe.context.context (/Users/dan/Websites/wpdtrt-npm-scripts/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at Object.<anonymous> (/Users/dan/Websites/wpdtrt-npm-scripts/test/tasks/scripts.spec.js:70:1)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /Users/dan/Websites/wpdtrt-npm-scripts/node_modules/mocha/lib/mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/dan/Websites/wpdtrt-npm-scripts/node_modules/mocha/lib/mocha.js:331:14)
    at Mocha.run (/Users/dan/Websites/wpdtrt-npm-scripts/node_modules/mocha/lib/mocha.js:809:10)
    at exports.singleRun (/Users/dan/Websites/wpdtrt-npm-scripts/node_modules/mocha/lib/cli/run-helpers.js:108:16)
    at exports.runMocha (/Users/dan/Websites/wpdtrt-npm-scripts/node_modules/mocha/lib/cli/run-helpers.js:142:13)
    at exports.handler (/Users/dan/Websites/wpdtrt-npm-scripts/node_modules/mocha/lib/cli/run.js:292:3)
    at Object.runCommand (/Users/dan/Websites/wpdtrt-npm-scripts/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/Users/dan/Websites/wpdtrt-npm-scripts/node_modules/yargs/yargs.js:1096:28)
    at Object.parse (/Users/dan/Websites/wpdtrt-npm-scripts/node_modules/yargs/yargs.js:575:25)
    at exports.main (/Users/dan/Websites/wpdtrt-npm-scripts/node_modules/mocha/lib/cli/cli.js:68:6)
    at Object.<anonymous> (/Users/dan/Websites/wpdtrt-npm-scripts/node_modules/mocha/bin/mocha:162:29)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by dotherightthing** [comment]
```js
"test:internal": "chmod a+x test/scripts/*.sh && ./test/scripts/teardown.sh && ./test/scripts/setup.sh && mocha --recursive \"./test/**/*.spec.js\" --full-trace",
```

test/tasks/scripts.spec.js:

```
    const packageJson = {
        publisher: process.env.npm_package_homepage.replace('https://github.com/', '').split('/')[0],
        name: process.env.npm_package_homepage.replace('https://github.com/', '').split('/')[1]
    };
```

Cannot read properties of undefined (reading 'replace') = `process.env.npm_package_homepage` is missing
