### ISSUE TITLE
CI: test (PHP test) fails with "Could not find /tmp/wordpress-tests-lib/includes/functions.php"

### ISSUE THREAD

**Issue by dotherightthing** [dotherightthing/wpdtrt-npm-scripts#63]
```sh

  3) scripts
       wordpress-plugin
         test
           runs WordPress (PHP) unit tests:

      AssertionError: PHP Fatal error:  Uncaught Exception: Could not find /tmp/wordpress-tests-lib/includes/functions.php, have you run bin/install-wp-tests.sh ? in /home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/vendor/dotherightthing/wpdtrt-gallery/tests/bootstrap.php:18
Stack trace:
#0 /home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/vendor/dotherightthing/wpdtrt-gallery/vendor/phpunit/phpunit/src/Util/FileLoader.php(57): include_once()
#1 /home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/vendor/dotherightthing/wpdtrt-gallery/vendor/phpunit/phpunit/src/Util/FileLoader.php(45): PHPUnit\Util\FileLoader::load('/home/runner/wo...')
#2 /home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/vendor/dotherightthing/wpdtrt-gallery/vendor/phpunit/phpunit/src/TextUI/Command.php(1058): PHPUnit\Util\FileLoader::checkAndLoad('/home/runner/wo...')
#3 /home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/vendor/dotherightthing/wpdtrt-gallery/vendor/phpunit/phpunit/src/TextUI/Command.php(863): PHPUnit\TextUI\Command->handleBootstrap('/ho in /home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/vendor/dotherightthing/wpdtrt-gallery/tests/bootstrap.php on line 18: expected 'PHP Fatal error:  Uncaught Exception:…' to equal ''
      + expected - actual

      -PHP Fatal error:  Uncaught Exception: Could not find /tmp/wordpress-tests-lib/includes/functions.php, have you run bin/install-wp-tests.sh ? in /home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/vendor/dotherightthing/wpdtrt-gallery/tests/bootstrap.php:18
      -Stack trace:
      -#0 /home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/vendor/dotherightthing/wpdtrt-gallery/vendor/phpunit/phpunit/src/Util/FileLoader.php(57): include_once()
      -#1 /home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/vendor/dotherightthing/wpdtrt-gallery/vendor/phpunit/phpunit/src/Util/FileLoader.php(45): PHPUnit\Util\FileLoader::load('/home/runner/wo...')
      -#2 /home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/vendor/dotherightthing/wpdtrt-gallery/vendor/phpunit/phpunit/src/TextUI/Command.php(1058): PHPUnit\Util\FileLoader::checkAndLoad('/home/runner/wo...')
      -#3 /home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/vendor/dotherightthing/wpdtrt-gallery/vendor/phpunit/phpunit/src/TextUI/Command.php(863): PHPUnit\TextUI\Command->handleBootstrap('/ho in /home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/vendor/dotherightthing/wpdtrt-gallery/tests/bootstrap.php on line 18
      
      at Context.<anonymous> (file:///home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/test/tasks/scripts.spec.mjs:473:30)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by dotherightthing** [comment]
Related to #16 ?

**Comment by dotherightthing** [comment]
See #64
