### ISSUE TITLE
CI: wpunit installation fails (if app.uses.wpunit)

### ISSUE THREAD

**Issue by dotherightthing** [dotherightthing/wpdtrt-npm-scripts#64]
```sh
   1) scripts
       wordpress-plugin
         install
           dependencies
             wpunit:

      /tmp/wordpress
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (file:///home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/test/tasks/scripts.spec.mjs:268:34)
      at callFn (/home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/node_modules/mocha/lib/runnable.js:366:21)
      at Runnable.run (/home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/node_modules/mocha/lib/runnable.js:354:5)
      at Runner.runTest (/home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/node_modules/mocha/lib/runner.js:666:10)
      at /home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/node_modules/mocha/lib/runner.js:789:12
      at next (/home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/node_modules/mocha/lib/runner.js:581:14)
      at /home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/node_modules/mocha/lib/runner.js:591:7
      at next (/home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/node_modules/mocha/lib/runner.js:474:14)
      at Immediate._onImmediate (/home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/node_modules/mocha/lib/runner.js:559:5)
      at process.processImmediate (node:internal/timers:471:21)

  3) scripts
       wordpress-plugin
         test
           runs WordPress (PHP) unit tests:

      AssertionError: PHP Fatal error:  Uncaught Exception: Could not find /tmp/wordpress-tests-lib/includes/functions.php, have you run bin/install-wp-tests.sh ? in /home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/vendor/dotherightthing/wpdtrt-gallery/tests/bootstrap.php:18
Stack trace:
#0 /home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/vendor/dotherightthing/wpdtrt-gallery/vendor/phpunit/phpunit/src/Util/FileLoader.php(57): include_once()
#1 /home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/vendor/dotherightthing/wpdtrt-gallery/vendor/phpunit/phpunit/src/Util/FileLoader.php(45): PHPUnit\Util\FileLoader::load('/home/runner/wo...')
#2 /home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/vendor/dotherightthing/wpdtrt-gallery/vendor/phpunit/phpunit/src/TextUI/Command.php(1058): PHPUnit\Util\FileLoader::checkAndLoad('/home/runner/wo...')
#3 /home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/vendor/dotherightthing/wpdtrt-gallery/vendor/phpunit/phpunit/src/TextUI/Command.php(863): PHPUnit\TextUI\Command->handleBootstrap('/ho in /home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/vendor/dotherightthing/wpdtrt-gallery/tests/bootstrap.php on line 18: expected 'PHP Fatal error:  Uncaught Exception:…' to equal ''
      + expected - actual

      -PHP Fatal error:  Uncaught Exception: Could not find /tmp/wordpress-tests-lib/includes/functions.php, have you run bin/install-wp-tests.sh ? in /home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/vendor/dotherightthing/wpdtrt-gallery/tests/bootstrap.php:18
      -Stack trace:
      -#0 /home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/vendor/dotherightthing/wpdtrt-gallery/vendor/phpunit/phpunit/src/Util/FileLoader.php(57): include_once()
      -#1 /home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/vendor/dotherightthing/wpdtrt-gallery/vendor/phpunit/phpunit/src/Util/FileLoader.php(45): PHPUnit\Util\FileLoader::load('/home/runner/wo...')
      -#2 /home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/vendor/dotherightthing/wpdtrt-gallery/vendor/phpunit/phpunit/src/TextUI/Command.php(1058): PHPUnit\Util\FileLoader::checkAndLoad('/home/runner/wo...')
      -#3 /home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/vendor/dotherightthing/wpdtrt-gallery/vendor/phpunit/phpunit/src/TextUI/Command.php(863): PHPUnit\TextUI\Command->handleBootstrap('/ho in /home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/vendor/dotherightthing/wpdtrt-gallery/tests/bootstrap.php on line 18
      
      at Context.<anonymous> (file:///home/runner/work/wpdtrt-npm-scripts/wpdtrt-npm-scripts/test/tasks/scripts.spec.mjs:473:30)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by dotherightthing** [comment]
See 64b8aa02a44645264758c56a06abef40a010a5b2 and fc608ef74f1651c89dceb3a5158071a70bd40b42

**Comment by dotherightthing** [comment]
In https://github.com/dotherightthing/wpdtrt-gallery/blob/1a411e42968e51637a6120176ef14708e8b0017e/tests/bootstrap.php#L13-L15, need to pass in the tmp dir used by Github Actions, or query it using PHP. Currently it seems to return `tmp` which gives this bogus path: `/tmp/tmp/wordpress-tests-lib/includes/functions.php`

**Comment by dotherightthing** [comment]
Resolved by using https://www.npmjs.com/package/os:

`import { tmpdir } from 'os';`
